### ISSUE TITLE
No gradient clipping in parallel version lstm training?

### ISSUE THREAD

**Issue by lifelongeek** [yajiemiao/eesen#1]
Hi
I saw that gradient clipping from non-parallel version of lstm code. (i.e. bilstm-layer.h)
But I cannot see corresponding part in parallel version of lstm. (i.e. bilstm-parallel-layer.h)
Although training seems fine for almost all cases ( I tried with several different size architecture on swbd), I wonder whether there is some reason you did not include clipping in parallel version lstm.

**Comment by yajiemiao** [comment]
The class BiLstmParallel inherits BiLstm. They share the same Update() function.

**Comment by lifelongeek** [comment]
Oh I didn't see that part. I am sorry for my mistake.
