### ISSUE TITLE
where is prune-lm?

### ISSUE THREAD

**Issue by NewEricWang** [yajiemiao/eesen#14]
Hi，
     I try to run WSJ example, but I get a error:
     local/wsj_data_prep.sh: line 161: prune-lm: command not found

```
Where is the tool "prune-lm"?
```

**Comment by yajiemiao** [comment]
you should install IRSTLM which is automatically installed after you run "make" under tools

**Comment by NewEricWang** [comment]
get it! 
Thank you!
