### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by vince62s** [yajiemiao/eesen#3]
Hi there,
I am willing to test but before may I ask a few questions:
- is GPU just recommended or necessary ? I intend to run a mulitcore machines.
- can I use grid-engine like with Kaldi queue.pl ?
- how does it take to train for 108hours tedlium 1 in your experience ?
- how long would that take for 30hours of audio and do you think it is enough to get decent results ?
  Cheers,
  Vinny.

**Comment by yajiemiao** [comment]
- GPU is required
- Yes
- it depends on the performance of your GPU card. With a Tesla K80, it took 3 days
- Probably not. My observation is that CTC performs better with large amounts of data
