### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by madhavsund** [yajiemiao/eesen#6]
I get the following syntax error  and negative token accuracy while running on my own dataset
kindly help me to sort out....
# 

```
                      Model Training                           
```
# 

steps/train_ctc_parallel.sh --add-deltas true --num-sequence 10 --learn-rate 0.00004 --report-step 1000 --halving-after-epoch 12 --feats-tmpdir exp/train_phn_l2_c200/XXXXX data/train_tr95 data/train_cv05 exp/train_phn_l2_c200
feat-to-len scp:data/train_tr95/feats.scp ark,t:- 
feat-to-len scp:data/train_cv05/feats.scp ark,t:- 
copy-feats 'ark,s,cs:apply-cmvn --norm-vars=true --utt2spk=ark:data/train_tr95/utt2spk scp:data/train_tr95/cmvn.scp scp:exp/train_phn_l2_c200/train.scp ark:- |' ark,scp:exp/train_phn_l2_c200/Ofwfy/train.ark,exp/train_phn_l2_c200/train_local.scp 
apply-cmvn --norm-vars=true --utt2spk=ark:data/train_tr95/utt2spk scp:data/train_tr95/cmvn.scp scp:exp/train_phn_l2_c200/train.scp ark:- 
LOG (apply-cmvn:main():apply-cmvn.cc:129) Applied cepstral mean and variance normalization to 2823 utterances, errors on 0
LOG (copy-feats:main():copy-feats.cc:100) Copied 2823 feature matrices.
copy-feats 'ark,s,cs:apply-cmvn --norm-vars=true --utt2spk=ark:data/train_cv05/utt2spk scp:data/train_cv05/cmvn.scp scp:exp/train_phn_l2_c200/cv.scp ark:- |' ark,scp:exp/train_phn_l2_c200/Ofwfy/cv.ark,exp/train_phn_l2_c200/cv_local.scp 
apply-cmvn --norm-vars=true --utt2spk=ark:data/train_cv05/utt2spk scp:data/train_cv05/cmvn.scp scp:exp/train_phn_l2_c200/cv.scp ark:- 
LOG (apply-cmvn:main():apply-cmvn.cc:129) Applied cepstral mean and variance normalization to 151 utterances, errors on 0
LOG (copy-feats:main():copy-feats.cc:100) Copied 151 feature matrices.
TRAINING STARTS [2016-Feb-11 09:46:16]
[NOTE] TOKEN_ACCURACY refers to token accuracy, i.e., (1.0 - token_error_rate).
**EPOCH 1 RUNNING ... ENDS [2016-Feb-11 09:50:04]: lrate 4e-05, TRAIN ACCURACY -71.7361%, VALID ACCURACY -75.7551%
(standard_in) 1: syntax error
(standard_in) 1: syntax error
steps/train_ctc_parallel.sh: line 163: [: too many arguments
(standard_in) 1: syntax error
steps/train_ctc_parallel.sh: line 175: [: 1: unary operator expected
EPOCH 2 RUNNING ... ENDS [2016-Feb-11 09:53:56]: lrate 4e-05, TRAIN ACCURACY -71.7361%, VALID ACCURACY -75.7551%
(standard_in) 1: syntax error
(standard_in) 1: syntax error
steps/train_ctc_parallel.sh: line 163: [: too many argument**

**Comment by yajiemiao** [comment]
Looks like no training has happened at all.
Can you look into the more detailed log exp/train_phn_l2_c200/log/tr.iter1.log?

**Comment by madhavsund** [comment]
I couldn't get any clue... 
I have attached the log file...

[tr.iter1.txt](https://github.com/yajiemiao/eesen/files/127471/tr.iter1.txt)

**Comment by madhavsund** [comment]
I modified the transcripts and now it is working but the accuracy keeps constant 
NO updates in network..

LOG (copy-feats:main():copy-feats.cc:100) Copied 184 feature matrices.
Initializing model as exp/train_phn_l5_c200/nnet/nnet.iter0
TRAINING STARTS [2016-Feb-12 14:08:58]
[NOTE] TOKEN_ACCURACY refers to token accuracy, i.e., (1.0 - token_error_rate).
EPOCH 1 RUNNING ... ENDS [2016-Feb-12 14:17:41]: lrate 4e-05, TRAIN ACCURACY 3.7802%, VALID ACCURACY 4.5504%
EPOCH 2 RUNNING ... ENDS [2016-Feb-12 14:26:34]: lrate 4e-05, TRAIN ACCURACY 3.7802%, VALID ACCURACY 4.5504%
EPOCH 3 RUNNING ... 
\

**Comment by yajiemiao** [comment]
Training simply blows up, as shown by -1e+30 objective.
This is likely to happen if a label (e.g., 100) from label sequences exceeds the range of softmax layer (e.g., 0 - 90). You may check if the number of labels truly corresponds to the size of the softmax layer.

**Comment by madhavsund** [comment]
I checked the transcript every thing is ok.I tried with tedlium corpus ( with 200 waves)  , I get the same error...
I have attached log of tedlium corpus....kindly help me to resolve..

[tr.iter1.txt](https://github.com/yajiemiao/eesen/files/133659/tr.iter1.txt)

**Comment by yajiemiao** [comment]
are you using CPU rather than GPU for training? Eesen does not support CPU training.

**Comment by madhavsund** [comment]
I have configured for GPU during installation and  I use  NIVIDEA  NVS 300 card.
How to check whether it runs on cpu or gpu?

**Comment by yajiemiao** [comment]
If you had GPU running, you should have seen something like the following at the beginning of the log file.

LOG (train-ctc-parallel:SelectGpuIdAuto():cuda-device.cc:262) Selecting from 1 GPUs
LOG (train-ctc-parallel:SelectGpuIdAuto():cuda-device.cc:277) cudaSetDevice(0): Tesla K80       free:12163M, used:124M, total:12287M, free/total:0.989858
LOG (train-ctc-parallel:SelectGpuIdAuto():cuda-device.cc:310) Selected device: 0 (automatically)
LOG (train-ctc-parallel:FinalizeActiveGpu():cuda-device.cc:194) The active GPU is [0]: Tesla K80        free:12149M, used:138M, total:12287M, free/total:0.988719 version 3.7
LOG (train-ctc-parallel:PrintMemoryUsage():cuda-device.cc:334) Memory used: 0 bytes.

**Comment by madhavsund** [comment]
yes, the problem was with GPU .  now GPU is configured correctly and it is working ..
Thanks a lot...
